In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = {
    "지점": [
        "강남", "강남", "강남", "홍대", "홍대",
        "홍대", "종로", "종로", "종로", "종로"
    ],
    "메뉴": [
        "아메리카노", "라떼", "케이크",
        "아메리카노", "라떼", "케이크",
        "아메리카노", "라떼", "케이크", "아메리카노"
    ],
    "가격": [
        4500, 5500, 7000,
        4500, 5500, 7000,
        4500, 5500, 7000, 4500
    ],
    "판매량": [
        120, 80, 30,
        150, 60, 45,
        90, 100, 25, 110
    ],
    "평점": [
        4.5, 4.2, 4.8,
        4.7, 3.9, 4.6,
        4.1, np.nan, 4.9, 4.3
    ]
}

df = pd.DataFrame(data)

In [11]:
# df의 행/열 개수, 컬럼 이름, 각 컬럼의 자료형을 확인하세요.
df.head()
df.dtypes

지점         str
메뉴         str
가격       int64
판매량      int64
평점     float64
dtype: object

In [15]:
# 처음 5개의 데이터만 출력하세요.
df[["지점", "메뉴", "판매량"]]

   지점     메뉴  판매량
0  강남  아메리카노  120
1  강남     라떼   80
2  강남    케이크   30
3  홍대  아메리카노  150
4  홍대     라떼   60
5  홍대    케이크   45
6  종로  아메리카노   90
7  종로     라떼  100
8  종로    케이크   25
9  종로  아메리카노  110

In [17]:
# 판매량이 100 이상인 데이터만 추출하세요.
df_mask = df["판매량"] >= 100
df[df_mask]

   지점     메뉴    가격  판매량   평점
0  강남  아메리카노  4500  120  4.5
3  홍대  아메리카노  4500  150  4.7
7  종로     라떼  5500  100  NaN
9  종로  아메리카노  4500  110  4.3

In [22]:
# 판매량이 100 이상이면서 메뉴가 아메리카노인 데이터만 추출하세요.
df_mask  = (df["메뉴"] == "아메리카노") & (df["판매량"] >= 100)
df[df_mask]

   지점     메뉴    가격  판매량   평점
0  강남  아메리카노  4500  120  4.5
3  홍대  아메리카노  4500  150  4.7
7  종로  아메리카노  5500  100  NaN
9  종로  아메리카노  4500  110  4.3

In [10]:
# "매출"이라는 새로운 컬럼을 만드세요.
df["매출"] = df["가격"] * df["판매량"]
df

   지점     메뉴    가격  판매량   평점      매출
0  강남  아메리카노  4500  120  4.5  540000
1  강남     라떼  5500   80  4.2  440000
2  강남    케이크  7000   30  4.8  210000
3  홍대  아메리카노  4500  150  4.7  675000
4  홍대     라떼  5500   60  3.9  330000
5  홍대    케이크  7000   45  4.6  315000
6  종로  아메리카노  4500   90  4.1  405000
7  종로     라떼  5500  100  NaN  550000
8  종로    케이크  7000   25  4.9  175000
9  종로  아메리카노  4500  110  4.3  495000

In [36]:
# 매출이 가장 높은 행을 찾아서 지점, 메뉴, 매출을 출력하세요. 지금 배운 max()나 argmax()/idxmax() 등을 생각해보세요.

In [15]:
# groupby()를 이용해서 지점별 총 매출을 구하세요.
df.groupby("지점").sum()["매출"]
df.groupby("지점")["매출"].sum()

지점
강남    1190000
종로    1625000
홍대    1320000
Name: 매출, dtype: int64

In [22]:
# roupby()를 이용해서 메뉴별 평균 판매량을 구하세요.
round(df.groupby("메뉴")["판매량"].mean(), 2)

메뉴
라떼        80.00
아메리카노    117.50
케이크       33.33
Name: 판매량, dtype: float64

In [50]:
# 지점별로 데이터가 몇 개씩 있는지 구하세요.
df.groupby("지점").size()

지점
강남    3
종로    4
홍대    3
dtype: int64

In [49]:
# "평점"에 결측값(NaN)이 몇 개 있는지 확인하세요.
df["평점"].isna().sum()

np.int64(1)

In [59]:
# apply()와 함수를 이용해서 "평가"라는 파생변수를 만드세요.
# 평점이 NaN → "평가 없음"
# 평점 >= 4.5 → "우수"
# 나머지 → "보통"

def df_score(score):
    if pd.isna(score):
        return "평가 없음"
    if score >= 4.5:
        return "우수"
    else:
        return "보통"

df["평가"] = df["평점"].apply(df_score)
df

   지점     메뉴    가격  판매량   평점      매출     평가
0  강남  아메리카노  4500  120  4.5  540000     우수
1  강남     라떼  5500   80  4.2  440000     보통
2  강남    케이크  7000   30  4.8  210000     우수
3  홍대  아메리카노  4500  150  4.7  675000     우수
4  홍대     라떼  5500   60  3.9  330000     보통
5  홍대    케이크  7000   45  4.6  315000     우수
6  종로  아메리카노  4500   90  4.1  405000     보통
7  종로     라떼  5500  100  NaN  550000  평가 없음
8  종로    케이크  7000   25  4.9  175000     우수
9  종로  아메리카노  4500  110  4.3  495000     보통

In [67]:
# 전체 판매량의 평균, 편차, 편차의 제곱, 분산, 표준편차를 직접 구해보세요. 처음부터 std()를 쓰지 말고 지금 배운 방식으로 계산합니다.
mean = df["판매량"].mean()
print(df["판매량"] - mean)
df["편차제곱"] = (df["판매량"] - mean) ** 2
df["편차제곱"].mean() ** 0.5

0    39.0
1    -1.0
2   -51.0
3    69.0
4   -21.0
5   -36.0
6     9.0
7    19.0
8   -56.0
9    29.0
Name: 판매량, dtype: float64

np.float64(38.781438859330635)